from smartinmate_automation import SmartInmateAutomation
from ai_chat import LMStudioChat
import config
import time
import re

def extract_inmate_id(body_text):
    match = re.search(r'\b(\d{9,})\b', body_text)
    return match.group(1) if match else None

unread=True

def run_bot():
    bot = SmartInmateAutomation(config.SMARTINMATE_USERNAME, config.SMARTINMATE_PASSWORD, headless=unread)
    ai = LMStudioChat()  # Uses Deepseek by default
    bot.login()
    if unread:
        print("Logged in. Scanning first 5 unread messages...")
        unread_count = 0
        max_unread = 5
        while unread_count < max_unread:
            rows = bot.driver.find_elements("css selector", ".row-fluid")
            unread_row = None
            for row in rows:
                try:
                    status_span = row.find_element("css selector", ".span1")
                    if '●' in status_span.text:
                        unread_row = row
                        break
                except Exception:
                    continue
            if not unread_row:
                print("No more unread messages found.")
                break
            try:
                bot.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", unread_row)
                time.sleep(0.5)
                unread_row.click()
                time.sleep(2)
                body_text = bot.driver.find_element("tag name", "body").text
                sender_id = extract_inmate_id(body_text) or 'unknown'
                marker = 'Reply   Delete   Messages'
                splits = body_text.split(marker)
                content = ''
                if len(splits) > 2:
                    content = splits[1].strip()
                else:
                    content = body_text
                print(f"[Unread] Inmate ID: {sender_id}")
                print(f"Content: {content}")
                print("Getting AI response...")
                ai_reply = ai.get_response(sender_id, content)
                ai_reply = (
                    "Thanks for using Justice Companion.\n"
                    "This response was generated by an artificial intelligence system based on publicly available information.\n"
                    "It is not legal advice and should not be relied upon as a substitute for consultation with a qualified attorney. \n"
                    "You are solely responsible for any actions you take based on this information.\n\n\n"
                    + ai_reply
                )
                #limit the AI reply to 30000 characters
                ai_reply = ai_reply[:30000]
                print("AI response generated:")
                print(f"AI Reply: {ai_reply}")
                print("Replying to the message...")
                bot.reply_to_message(ai_reply)
                print("Reply attempted. Moving to next message.")
                unread_count += 1
                bot.driver.back()
                time.sleep(30)
            except Exception as e:
                print(f"Error processing unread message {unread_count+1}: {e}")
                try:
                    bot.driver.back()
                    time.sleep(2)
                except Exception:
                    pass
        print(f"Processed {unread_count} unread messages.")
    else:
        print("Logged in. Reading the first message (read or unread)...")
        try:
            first_row = bot.driver.find_elements("css selector", ".row-fluid")[0]
            bot.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", first_row)
            time.sleep(0.5)
            first_row.click()
            time.sleep(2)
            body_text = bot.driver.find_element("tag name", "body").text
            sender_id = extract_inmate_id(body_text) or 'unknown'
            marker = 'Reply   Delete   Messages'
            splits = body_text.split(marker)
            content = ''
            if len(splits) > 2:
                content = splits[1].strip()
            else:
                content = body_text
            print(f"Inmate ID: {sender_id}")
            print(f"Content: {content}")
            print("Getting AI response...")
            ai_reply = ai.get_response(sender_id, content)
            ai_reply = (
                "Thanks for using Justice Companion.\n"
                "This response was generated by an artificial intelligence system based on publicly available information.\n"
                "It is not legal advice and should not be relied upon as a substitute for consultation with a qualified attorney. \n"
                "You are solely responsible for any actions you take based on this information.\n\n\n"
                + ai_reply
            )
            ai_reply = ai_reply[:30000]
            print("AI response generated:")
            print(f"AI Reply: {ai_reply}")
            print("Replying to the message...")
            bot.reply_to_message(ai_reply)
            print("Reply attempted.")
            bot.driver.back()
            time.sleep(30)
        except Exception as e:
            print(f"Error processing first message: {e}")
            try:
                bot.driver.back()
                time.sleep(2)
            except Exception:
                pass
    print("Bot run complete.")
    bot.driver.quit()

if __name__ == '__main__':
    while True:
        print("Starting bot run...")
        run_bot()
        print("Sleeping for 10 minutes...")
        time.sleep(600)
